---
application:
  name: "musicbot"
  project: "Music Player"
  organization: "QoveryCommunity"
databases:
- type: "MONGODB"
  name: "idkwhatever"
  version: "4.4"
routers:
- name: "main-musicbot"
  routes:
  - application_name: "musicbot"
    paths:
    - "/*"
